name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Construção e envio da Imagem Docker
        run: echo "Executando o comando Docker build"
        uses: docker/build-push-action@v6
        with:
          context: fake-shop/src
          push: true
          file: fake-shop/src/Dockerfile
          tags: | 
            leopoldopeixoto/fake-shop:latest
            leopoldopeixoto/fake-shop:v${{  github.run_number }}


  cd:
      runs-on: ubuntu-latest
      needs: [ci]
      steps:
        - name: Autenticar na AWS
          run: echo "Executando o comando aws configure"
        - name: Configurar o Kubectl
          run: echo "Executando o comando aws eks update-kubeconfig"
        - name: Deploy dos manifestos Kubernetes
          run: echo "Executando o comando kubectl apply"
      
